### ISSUE TITLE
problem running default esp_fit_and_flex.py

### ISSUE THREAD

**Issue by ph265** [jszopi/repESP#13]
Hi Jan,  I've downloaded the new scripts (6pm 4th Sept) and tried to run this script in its default version (ie as given) and it is finishing with an error ...

Starting minimization of charge ratio.

FOUND optimal heavy ratio: 0.4871 with RRMS of 0.011621

Number of charges sampled along each axis: 21
Reporting contour surface areas:
  1% contour area: 0.00353
  5% contour area: 0.03065
 10% contour area: 0.06633
 20% contour area: 0.14358
 30% contour area: 0.22719
 50% contour area: 0.41455
100% contour area: 0.75808
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/contour.py:370: RuntimeWarning: invalid value encountered in true_divide
  dist = np.add.reduce(([(abs(s)[i] / L[i]) for i in range(xsize)]), -1)

**Comment by jszopi** [comment]
This is not an error, but a warning. The 2D contour plot should have been generated, is it correct?

`matplotlib` [claim](https://sourceforge.net/p/matplotlib/mailman/message/32471728/) to handle missing values but if there _are_ missing values, it's probably a bug in the code, so I'd like to investigate.

I couldn't reproduce this warning. Could you please post the full traceback? Does it happen every time you try? It may be something to do with the input, are you sure you are running the default molecule?
