### ISSUE TITLE
data print for charge differences in esp_fit.py

### ISSUE THREAD

**Issue by ph265** [jszopi/repESP#8]
I'd like to see more than just the difference between two atoms in the section
Checking differences between raw and equivalenced charges ...
perhaps a limit which I can change above which all differences are printed eg if absolute differences are greater than 0.01 they are printed

**Comment by jszopi** [comment]
The function call responsible for this part of output is `compare_charges` on line 207 of `esp_fit.py`. This function takes an optional parameter `thresh`, which will do exactly what you want, so you can just add it after a comma:
```
print(charges.compare_charges(esp_charge_type, 'resp', g.molecule,
      esp_equiv_molecule, thresh=0.01))
```
Note that you can set this parameter to 0 to show differences for all atoms.

Also note that the CLI script `average.py` incorporates this functionality with the `--thresh` option.
